#!/usr/bin/env bash

source ./lib.sh

read -rp "Username (email address): " email
read -rsp "Password for '$email': " password

curl \
  --url "$uaa_url/oauth/token" \
  --user "$clientid:$clientsecret" \
  --data-urlencode 'grant_type=password' \
  --data-urlencode "username=$email" \
  --data-urlencode "password=$password"
