#!/usr/bin/env bash

set -o errexit

# Create local bin dir (if it doesn't exist) and add it to PATH
[[ -d "$HOME/bin" ]] || mkdir "$HOME/bin/"
echo 'export PATH=$PATH:$HOME/bin' >> "$HOME/.bashrc"

# Retrieve btp CLI installer and make executable
curl \
  --remote-name \
  --location \
  --url "https://raw.githubusercontent.com/SAP-samples/sap-tech-bytes/2021-09-01-btp-cli/getbtpcli" \
  && chmod +x getbtpcli

# Run the btp CLI installer then remove it
yes | ./getbtpcli
rm ./getbtpcli

# Also install the CF CLI in case the MTA Tools extension wasn't specified when setting up the Dev Space
curl \
  --location \
  --url "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" \
  | tar \
    --directory "$HOME/bin/" \
    --extract \
    --gunzip \
    --file - \
    cf cf8

