#!/usr/bin/env bash

# Calls the Entitlements Service API for "Regions for Global Accounts"

source ./lib.sh

declare endpoint token_file token

token_file="${1:?Specify name of file containing token data}"

endpoint="$(jq -r .endpoints.entitlements_service_url "$service_key_file")"
endpoint+="/entitlements/v1/globalAccountAllowedDataCenters"

token="$(jq -r .access_token "$token_file")"

curl \
  --url "$endpoint" \
  --header "Authorization: Bearer $token"

